---expolre all object in the Database
select*
from INFORMATION_SCHEMA.tables

--expolre ALL COLUMNS IN THE DATABASE 
SELECT*
FROM INFORMATION_SCHEMA.COLUMNS

--EXPLORE ALL COLUMNS IN THE DATABASE
SELECT*
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'DIM_CUSTOMERS'

--EXPLORE ALL COUNTRIES OUR CUSTOMERS COME FROM 
SELECT DISTINCT COUNTRY FROM GOLD.dim_customers

--EXPLORE ALL PRODUCT CATEGORIES "THE MAJOR DIVISIONS"
SELECT DISTINCT CATEGORY ,subcategory ,Product_name FROM GOLD.dim_products
order by 1,2,3

-- find the date of the first and last order
select min(order_date) as first_order_date,
max(order_date)as last_order_date
from gold.fact_sales

--how many years of sales are available
select
datediff(year,min(order_date),max(order_date)) as order_range_years
from gold.fact_sales

--find the youngest and oldest customer
select
min(birthdate) as oldest_birthdate,
DATEDIFF(YEAR,min(birthdate),getdate()) as oldest_age,
datediff(year,max(birthdate),getdate()) as youngest,
max(birthdate) as youngest_birthdate
from gold.dim_customers

-- find the total sales
select sum(sales_amount) as total_sales
from gold.fact_sales

--find how many items are sold
select
sum(quantity) as sum_quantity
from gold.fact_sales

--find the average selling price
select avg(sales_amount) as avg_sales
from gold.fact_sales

--find the total number of orders
select
count(order_number) as total_numbers from gold.fact_sales
select
count( distinct order_number) as total_numbers from gold.fact_sales

--find the total number of products
select count(product_key) as total_product from gold.dim_products
select count( distinct product_key) as total_product from gold.dim_products

--find the total number of customers
select count(customer_key) as total_customers from gold.dim_customers

--find the total number of customers that has placed an order
select count(distinct customer_key) as total_customers from gold.fact_sales


--Generate a report that shows all key metrics of the business
select 'Total sales' as measure_name,sum(sales_amount) as measure_value from gold.fact_sales
union all
select'Total Quantity' as measure_name,sum(quantity)  from gold.fact_sales
union all
select 'Average Price',avg(price)from gold.fact_sales
union all 
select'Total nr.orders',count(distinct order_number) from gold.fact_sales
union all 
select'Total nr.Products',count(product_name) from gold.dim_products
union all 
select'Total nr.Customers',count(customer_key) from gold.dim_customers

--find total customer by countries
select
country,
count(customer_key) as total_customers
from gold.dim_customers
group by country
order by total_customers

--Find total customers by gender
select
gender,
count(customer_key)as total_customers
from gold.dim_customers
group by gender
order by total_customers desc

--find total product by category
select
category,
count(product_key)as total_products
from gold.dim_products
group by category
order by total_products DESC

--what is the average costs in each category?
select
category,
avg(cost) as avg_cost
from gold.dim_products
group by category
order by avg_cost desc

--what is the total revenue generated for each category
select 
p.category,
sum(f.sales_amount) total_revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key
group by p.category
order by total_revenue desc

--what is the total generated by each customer?
select
c.customer_key,
c.first_name,
c.last_name,
sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_customers c
on c.customer_key = f.customer_key
group by 
c.customer_key,
c.first_name,
c.last_name
order by total_revenue desc

--what is the distribution of items sold across countries

select
c.country,
sum(f.quantity) as total_sold_items
from gold.fact_sales f
left join gold.dim_customers c
on c.customer_key = f.customer_key
group by 
c.country
order by total_sold_items desc

--which 5 products generate the highest revenue?
select top 5
p.product_name,
sum(f.sales_amount)total_revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key
group by p.product_name
order by total_revenue desc

select*
from(
select top 5
p.product_name,
sum(f.sales_amount)total_revenue,
row_number()over(order by sum(f.sales_amount) desc)as rank_products
from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key
group by p.product_name)t
where rank_products <= 5

--what are 5 worst-performing products in terms of sales

select top 5
p.product_name,
sum(f.sales_amount)total_revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key
group by p.product_name
order by total_revenue 

--find the top 10 customers who have generated the highest revenue
select top 10
c.customer_key,
c.first_name,
c.last_name,
sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_customers c
on c.customer_key = f.customer_key
group by 
c.customer_key,
c.first_name,
c.last_name
order by total_revenue desc

--the 3 customers with the fewest order placed
select top 3
c.customer_key,
c.first_name,
c.last_name,
count(distinct order_number) as total_orders
from gold.fact_sales f
left join gold.dim_customers c
on c.customer_key = f.customer_key
group by 
c.customer_key,
c.first_name,
c.last_name
order by total_orders 

